#!/bin/bash

build() {
    local mod
    
    add_module dm-crypt
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules '/crypto'
    fi
    
    add_binary "cryptsetup"
    add_binary "dmsetup"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    
    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows for an encrypted root device. Unlike the current official hook this one can make use of a detached header with the cryptheader parameter. As the original you can pass a cryptkey. Additionaly it is more error verbose and you can adjust the flow using the cryptflow parameter. See README for further details.
HELPEOF
}